//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SIGHeaderDelegate-Protocol.h"
#import "SIGScrollViewKeyValueObserverDelegate-Protocol.h"
#import "SIGTooltipPresenter-Protocol.h"

@class NSLayoutConstraint, NSString, SIGHeader, SIGScrollViewKeyValueObserver, SIGSubscreenViewControllerContentFade, UILayoutGuide, UIScrollView;

@interface SIGSubscreenView : UIView <SIGScrollViewKeyValueObserverDelegate, SIGTooltipPresenter, SIGHeaderDelegate>
{
    SIGHeader *_header;
    UIScrollView *_scrollView;
    SIGScrollViewKeyValueObserver *_observer;
    UIView *_backgroundView;
    UIView *_contentView;
    UILayoutGuide *_scrollViewLayoutGuide;
    SIGSubscreenViewControllerContentFade *_fade;
    NSLayoutConstraint *_fadeTopAnchor;
    _Bool _updatingInsets;
    struct UIEdgeInsets _additionalContentInsets;
    NSLayoutConstraint *_contentViewTopAnchor;
    _Bool _scrollBehaviorSuppressed;
    unsigned long long _style;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SIGHeader *header; // @synthesize header=_header;
@property(nonatomic, getter=isScrollBehaviorSupressed) _Bool scrollBehaviorSuppressed; // @synthesize scrollBehaviorSuppressed=_scrollBehaviorSuppressed;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void)updateScrollViewInsets;	// IMP=0x00000001001f336c
- (void)scrollViewContentOffsetDidChange:(id)arg1;	// IMP=0x0000000106fda4d4
- (void)dismissTooltip:(id)arg1;	// IMP=0x0000000106fda4c4
- (void)presentTooltip:(id)arg1 atPoint:(struct CGPoint)arg2 fromView:(id)arg3 forDuration:(double)arg4;	// IMP=0x0000000106fda438
- (void)header:(id)arg1 didChangeHeight:(double)arg2;	// IMP=0x00000001001f3360
- (void)_scrollViewBeingPanned;	// IMP=0x0000000106fda2dc
- (void)_stylize;	// IMP=0x00000001001760b8
- (id)scrollViewBottomAnchor;	// IMP=0x0000000106fda2d0
- (id)scrollViewTopAnchor;	// IMP=0x0000000100176034
- (void)safeAreaInsetsDidChange;	// IMP=0x0000000100212a94
- (id)initWithScrollView:(id)arg1;	// IMP=0x0000000106fd9da0
- (void)updateContentViewConstraintsRelativeToSectionHeader:(id)arg1;	// IMP=0x0000000106fd9bf4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100169484

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

