//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SIGSubscreenViewControllerContentFade : UIView
{
}

+ (Class)layerClass;	// IMP=0x000000010016a3fc
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000106fda724
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010016a150

@end

